### ISSUE TITLE
line numbers do not appear in all files in vs2019

### ISSUE THREAD

**Issue by geordis** [brianschmitt/relativenumber#22]
we are using microfocus visual cobol and editing dbl files.  All other file types have line numbers except for the cbl

![image](https://user-images.githubusercontent.com/55235430/70703039-8eee2080-1ccf-11ea-90f1-9be3bf509daf.png)
![image](https://user-images.githubusercontent.com/55235430/70703086-a0cfc380-1ccf-11ea-920e-d491c4ea41c1.png)

**Comment by brianschmitt** [comment]
Do you know if the CBL editor uses the normal line number column?
I assume line numbers are turned on?
Were the line numbers removed due to installing this extension?

**Comment by geordis** [comment]
Thank you!, they had them off by default in their own configuration settings. :)
