### ISSUE TITLE
VS 2017: after some VS update both columns are shown - relative and absolute

### ISSUE THREAD

**Issue by gluper** [brianschmitt/relativenumber#24]
Worked correctly for a long time, but now both columns are shown:

![both](https://user-images.githubusercontent.com/26507908/71355839-8ecc0b80-2580-11ea-89a8-8519f371ca46.PNG)

**Comment by brianschmitt** [comment]
2.8.0 of VsVim should now include this feature, and you no longer need my extension. See [VsVIM](https://github.com/VsVim/VsVim/issues/1909)
