### ISSUE TITLE
i got two line numbers

### ISSUE THREAD

**Issue by Marskey** [brianschmitt/relativenumber#25]
![image](https://user-images.githubusercontent.com/13499986/71390203-5983f400-263a-11ea-8a1d-10b86582e370.png)

**Comment by giggio** [comment]
I'm getting this too. How did you solve it, @Marskey ?

**Comment by Marskey** [comment]
Delete extensions relativenumber if you install the 2.80 vsvim. And add “set relativenumber “ into _vsvimrc
