### ISSUE TITLE
Update of VS2019 to 16.4.2 brings back the absolute line numbers

### ISSUE THREAD

**Issue by MartinL0815** [brianschmitt/relativenumber#26]
I just updated VS2019 to version 16.4.2.

After restarting and continuing my work I observed that now two columns of line numbers are visible.

> ![two columns of line numbers](https://user-images.githubusercontent.com/525700/71898679-39842280-315a-11ea-9bdb-6f8756b7b8aa.png)

If I disable the relative line numbers with `set nonu` the column with the absolute line numbers remains:

> ![disabled rel. line numbers](https://user-images.githubusercontent.com/525700/71898745-620c1c80-315a-11ea-8c2e-24a294a58bae.png)

Can you please provide a fix?

**Comment by brianschmitt** [comment]
The fix is to un-install my extension - VSVim 2.8 now includes this functionality and this extension is no longer needed if you are running that version.

**Comment by MartinL0815** [comment]
Thanks. Found the relativenumber setting and it works quite fine.
