### ISSUE TITLE
Very poor performance in Visual Studio 2015 Preview 3

### ISSUE THREAD

**Issue by connorjsmith** [brianschmitt/relativenumber#9]
With this extension enabled in 2015 Preview 3, navigating vertically (using arrow keys, hjkl or the mouse) becomes very slow. Regular VS2015 and Preview 2 had no such performance issues.

**Comment by brianschmitt** [comment]
Love to hear if this is still an issue for you - please try the newest release 1.5.0. Thanks

**Comment by connorjsmith** [comment]
Just tried the plugin again after a few months (on VS2017rc 26206.0) and the performance is much better. Everything seems to have been resolved!
